"use client";
import {useEffect,useMemo,useState} from "react";
const TERMS=["1st Term","2nd Term","3rd Term","4th Term"];
const COMPANIES=["Alpha","Bravo","Charlie","Delta"], PLATOONS=["1st","2nd","3rd","4th"];
const seed=[{id:1,roll:"24-001",name:"Ali Ahmed",company:"Alpha",platoon:"1st",term:"1st Term",restriction:12,offenses:[{date:"2026-09-20",offense:"Late reporting",source:"Duty Officer"}],marks:{quiz:91,mid:82,final:88,assign:86}}];
const pct=m=>Math.round(((+m.quiz||0)*.2+(+m.mid||0)*.25+(+m.final||0)*.35+(+m.assign||0)*.2)*100)/100;
export default function App(){
 const [login,setLogin]=useState(false),[u,setU]=useState(""),[p,setP]=useState(""),[cadets,setCadets]=useState(seed),[tab,setTab]=useState("dashboard"),[q,setQ]=useState(""),[notice,setNotice]=useState("");
 const [form,setForm]=useState({roll:"",name:"",company:"Alpha",platoon:"1st",term:"1st Term"});
 const [rid,setRid]=useState(null),[delta,setDelta]=useState(1),[off,setOff]=useState({offense:"",source:""});
 const [mid,setMid]=useState(null),[marks,setMarks]=useState({quiz:0,mid:0,final:0,assign:0});
 useEffect(()=>{try{const x=localStorage.getItem("pma-cadets-v7");if(x)setCadets(JSON.parse(x))}catch{}},[]);
 useEffect(()=>{if(login)localStorage.setItem("pma-cadets-v7",JSON.stringify(cadets))},[cadets,login]);
 const ranked=useMemo(()=>[...cadets].map(c=>({...c,percentage:pct(c.marks||{})})).sort((a,b)=>b.percentage-a.percentage).map((c,i)=>({...c,position:i+1})),[cadets]);
 const filtered=ranked.filter(c=>(c.roll+" "+c.name+" "+c.company+" "+c.platoon).toLowerCase().includes(q.toLowerCase()));
 const msg=x=>{setNotice(x);setTimeout(()=>setNotice(""),2500)};
 function signin(e){e.preventDefault();if(u==="admin"&&p==="PMA@123")setLogin(true);else alert("Invalid login. Use admin / PMA@123");}
 function add(e){e.preventDefault();if(!form.name.trim())return;setCadets(cs=>[{id:Date.now(),...form,restriction:0,offenses:[],marks:{quiz:0,mid:0,final:0,assign:0}},...cs]);setForm({...form,roll:"",name:""});msg("Cadet registered.");}
 function changeRestriction(id,n){setCadets(cs=>cs.map(c=>c.id===id?{...c,restriction:Math.max(0,c.restriction+n)}:c));}
 function addOffense(id){if(!off.offense.trim())return;setCadets(cs=>cs.map(c=>c.id===id?{...c,offenses:[...(c.offenses||[]),{...off,date:new Date().toISOString().slice(0,10)}],restriction:c.restriction+delta}:c));setOff({offense:"",source:""});setRid(null);msg("Restriction assigned.");}
 function promote(c){const i=TERMS.indexOf(c.term);if(i===3)return msg("Cadet is already in 4th Term.");if(!confirm("Promote "+c.name+" to "+TERMS[i+1]+"?"))return;setCadets(cs=>cs.map(x=>x.id===c.id?{...x,term:TERMS[i+1]}:x));msg("Cadet promoted.");}
 function saveMarks(){setCadets(cs=>cs.map(c=>c.id===mid?{...c,marks}:c));setMid(null);msg("Marks saved.");}
 if(!login)return <div className="login"><form onSubmit={signin}><h1>🛡️ PMA</h1><h2>Cadet Management Portal</h2><input placeholder="Username" value={u} onChange={e=>setU(e.target.value)}/><input type="password" placeholder="Password" value={p} onChange={e=>setP(e.target.value)}/><button>Sign In</button><small>Dummy login: admin / PMA@123</small></form></div>;
 return <main><aside><h2>🛡️ PMA</h2>{["dashboard","cadets","restrictions","marks","results"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x[0].toUpperCase()+x.slice(1)}</button>)}<button onClick={()=>setLogin(false)}>Logout</button></aside><section><header><div><h1>{tab[0].toUpperCase()+tab.slice(1)}</h1><p>Pakistan Military Academy · Cadet Management</p></div><b className="online">● Online</b></header>{notice&&<div className="notice">{notice}</div>}
 {tab==="dashboard"&&<><div className="cards"><Card n={cadets.length} t="Cadets"/><Card n={cadets.filter(c=>c.restriction>=60).length} t="Relegation threshold reached"/><Card n={ranked[0]?.percentage?.toFixed(1)||"0"} t="Top percentage"/><Card n={cadets.reduce((s,c)=>s+c.restriction,0)} t="Total restrictions"/></div><Panel title="Top Results">{ranked.slice(0,5).map(c=><div className="row" key={c.id}><b>#{c.position}</b><span>{c.roll} — {c.name}</span><strong>{c.percentage.toFixed(2)}%</strong></div>)}</Panel></>}
 {tab==="cadets"&&<><div className="toolbar"><input placeholder="Search cadets..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="two"><Panel title="Register Cadet"><form onSubmit={add} className="form">{Object.entries(form).map(([k,v])=><label key={k}>{k}<input value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button>Register</button></form></Panel><Panel title="Cadets">{filtered.map(c=><div className="cadet" key={c.id}><div><b>{c.roll} · {c.name}</b><small>{c.company} · {c.platoon} · {c.term}</small></div><button onClick={()=>promote(c)}>Promote</button></div>)}</Panel></div></>}
 {tab==="restrictions"&&<Panel title="Restriction Management"><p>60 or more restrictions = relegation threshold. Use +/− to correct counts. Each assignment can record offense and source.</p>{filtered.map(c=><div className="cadet" key={c.id}><div><b>{c.roll} · {c.name}</b><small className={c.restriction>=60?"danger":""}>{c.restriction} restrictions {c.restriction>=60?"· RELEGATION THRESHOLD":""}</small></div><div><button onClick={()=>changeRestriction(c.id,-1)}>−</button><b className="count">{c.restriction}</b><button onClick={()=>changeRestriction(c.id,1)}>+</button><button onClick={()=>setRid(c.id)}>Assign offense</button></div></div>)}</Panel>}
 {tab==="marks"&&<Panel title="Marks"><p>Weighted result: Quiz 20% · Mid Term 25% · Final Term 35% · Assignments 20%.</p>{filtered.map(c=><div className="cadet" key={c.id}><div><b>{c.roll} · {c.name}</b><small>{c.term} · {pct(c.marks||{}).toFixed(2)}%</small></div><button onClick={()=>{setMid(c.id);setMarks(c.marks||{quiz:0,mid:0,final:0,assign:0})}}>Edit Marks</button></div>)}</Panel>}
 {tab==="results"&&<Panel title="Overall Positions">{ranked.map(c=><div className="row" key={c.id}><b>#{c.position}</b><span>{c.roll} · {c.name} · {c.term}</span><strong>{c.percentage.toFixed(2)}%</strong></div>)}</Panel>}
 {rid&&<Modal title="Assign Restriction"><label>Count<input type="number" min="1" value={delta} onChange={e=>setDelta(+e.target.value||1)}/></label><label>Offense<input value={off.offense} onChange={e=>setOff({...off,offense:e.target.value})}/></label><label>Source / From<input value={off.source} onChange={e=>setOff({...off,source:e.target.value})}/></label><button onClick={()=>addOffense(rid)}>Assign</button><button className="light" onClick={()=>setRid(null)}>Cancel</button></Modal>}
 {mid&&<Modal title="Enter Marks">{["quiz","mid","final","assign"].map(k=><label key={k}>{k}<input type="number" min="0" max="100" value={marks[k]} onChange={e=>setMarks({...marks,[k]:e.target.value})}/></label>)}<button onClick={saveMarks}>Save</button><button className="light" onClick={()=>setMid(null)}>Cancel</button></Modal>}
 </section></main>
}
function Card({n,t}){return <div className="card"><b>{n}</b><span>{t}</span></div>}
function Panel({title,children}){return <div className="panel"><h2>{title}</h2>{children}</div>}
function Modal({title,children}){return <div className="modal"><div className="modalbox"><h2>{title}</h2>{children}</div></div>}